all:
	cp src/main.py bin/main.py
	cp src/codegenerator.pyc bin/codegenerator.pyc
	cp src/symtables.pyc bin/symtables.pyc
	cp src/TAC.pyc bin/TAC.pyc
	mv bin/main.py bin/codegen
	chmod +x bin/codegen
clean:
	rm -rf bin/*
