python three.py test/test1.txt test/test1.s
python three.py test/test2.txt test/test2.s
python three.py test/test3.txt test/test3.s
python three.py test/test4.txt test/test4.s
python three.py test/test5.txt test/test5.s
python three.py test/test6.txt test/test6.s
python three.py test/test7.txt test/test7.s
python three.py test/test8.txt test/test8.s
python three.py test/test9.txt test/test9.s
python three.py test/test10.txt test/test10.s
