python main.py test/test1.txt > test/test1.s
python main.py test/test2.txt > test/test2.s
python main.py test/test3.txt > test/test3.s
python main.py test/test4.txt > test/test4.s
python main.py test/test5.txt > test/test5.s
python main.py test/test6.txt > test/test6.s
python main.py test/test7.txt > test/test7.s
python main.py test/test8.txt > test/test8.s
python main.py test/test9.txt > test/test9.s
python main.py test/test10.txt > test/test10.s
python main.py test/test11.txt > test/test11.s
python main.py test/test12.txt > test/test12.s
python main.py test/test13.txt > test/test13.s
python main.py test/test14.txt > test/test14.s
